allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: false
  sharp: true
  vue-demi: true
minimumReleaseAge: 1440
blockExoticSubdeps: true
overrides:
  sharp: 0.33.4
  rollup: npm:@rollup/wasm-node
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - musl
    - glibc
