import { YouTube } from '@astro-community/astro-embed-youtube';

import Image from './components/Image.astro';
import MarkdownImage from './components/MarkdownImage.astro';
import Picture from './components/Picture.astro';
import ThemeBox from './components/ThemeBox.astro';

import {
	AffiliateLink,
	AmazonBook,
	Banner,
	Blockquote,
	Book,
	Bookshelf,
	ColorStack,
	ColorSwatch,
	DisplayBox,
	Divider,
	DownloadLink,
	EmailLink,
	Figure,
	Flag,
	Headline,
	ListItem,
	MoreLink,
	NetflixFlag,
	OdyseeVideo,
	OrderedList,
	PrimeVideoFlag,
	ProjectIntro,
	Pullquote,
	Spotify,
	Subheadline,
	Subsubheadline,
	Text,
	TextLink,
	Title,
	UnorderedList,
	Verse,
} from './components';

export const mapping = {
	a: TextLink,
	AffiliateLink,
	AmazonBook,
	Banner,
	Blockquote,
	blockquote: Blockquote,
	Book,
	Bookshelf,
	ColorStack,
	ColorSwatch,
	DisplayBox,
	DownloadLink,
	EmailLink,
	Figure,
	Flag,
	h1: Title,
	h2: Headline,
	h3: Subheadline,
	h4: Subsubheadline,
	h5: Subsubheadline,
	h6: Subsubheadline,
	hr: Divider,
	Image,
	img: MarkdownImage,
	li: ListItem,
	MarkdownImage,
	MoreLink,
	NetflixFlag,
	OdyseeVideo,
	ol: OrderedList,
	p: Text,
	Picture,
	PrimeVideoFlag,
	ProjectIntro,
	Pullquote,
	Spotify,
	ThemeBox,
	ul: UnorderedList,
	Verse,
	YouTube,
};

// Mapping for RSS feed to reduce the size of the feed
export const rssMapping = {
	AffiliateLink,
	AmazonBook,
	Banner,
	Blockquote,
	Book,
	Bookshelf,
	ColorStack,
	ColorSwatch,
	DisplayBox,
	DownloadLink,
	EmailLink,
	Figure,
	Flag,
	Image,
	MarkdownImage,
	MoreLink,
	NetflixFlag,
	OdyseeVideo,
	Picture,
	PrimeVideoFlag,
	ProjectIntro,
	Pullquote,
	Spotify,
	ThemeBox,
	Verse,
	YouTube,
};
